"""Orchestrator — self-governing loop: planner → reviewer → replanner → reviewer → ... until all goals met."""
import os
import re
import json
import uuid
from datetime import datetime

os.environ["OPENAI_AGENTS_DISABLE_TRACING"] = "1"

from .opnbrain import save_conversation

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("ORCHESTRATOR_MODEL", os.environ.get("OLLAMA_MODEL", "planner-model"))
OUTPUT_DIR = os.environ.get("AGENT_OUTPUT_DIR", os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "outputs", "sessions"))
TEMP_DIR = os.path.join(os.path.dirname(OUTPUT_DIR), "temp")
PLANNER_STORE = os.path.join(os.path.dirname(OUTPUT_DIR), "planner_store")
os.makedirs(TEMP_DIR, exist_ok=True)
os.makedirs(PLANNER_STORE, exist_ok=True)


def _brain_save(title: str, content: str, tags: list[str] | None = None):
    save_conversation(title=title, model=OLLAMA_MODEL, tags=tags or [],
                      is_chat=False, prompt="", response=content)


def _temp_save(key: str, content: str):
    path = os.path.join(TEMP_DIR, f"{key}.json")
    with open(path, "w") as f:
        json.dump({"key": key, "content": content, "timestamp": datetime.now().isoformat()}, f)


def _temp_load(key: str) -> str | None:
    path = os.path.join(TEMP_DIR, f"{key}.json")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)["content"]


async def _save_outputs(session_id: str, goal: str, plan: str = "", execution_log: str = "",
                        review_report: str = "", final_synthesis: str = "", task_log: str = "",
                        listing: str = "", research_data: str = "", analysis_report: str = ""):
    session_dir = os.path.join(OUTPUT_DIR, session_id)
    os.makedirs(session_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    toc = ["1. [Plan](plan.md)"]
    toc_map = {
        "research_data": ("2. [Research Data](research.md)", "research.md", f"# Research Data\n\n{research_data}"),
        "analysis_report": ("3. [Analysis Report](analysis.md)", "analysis.md", f"# Analysis Report\n\n{analysis_report}"),
        "execution_log": ("4. [Execution Log](execution.md)", "execution.md", f"# Execution Log\n\n{execution_log}"),
        "review_report": ("5. [Review Report](review.md)", "review.md", f"# Review Report\n\n{review_report}"),
        "listing": ("6. [Product Listing](listing.md)", "listing.md", f"# Product Listing\n\n{listing}"),
    }
    files = {"plan.md": f"# Plan\n\n**Session:** {session_id}\n\n{plan}"}
    for key, (toc_entry, fname, content) in toc_map.items():
        if locals()[key]:
            toc.append(toc_entry)
            files[fname] = content
    if final_synthesis:
        toc.append(f"{len(toc) + 1}. [Synthesis](synthesis.md)")
        files["synthesis.md"] = f"# Synthesis\n\n{final_synthesis}"
    if task_log:
        toc.append(f"{len(toc) + 1}. [Task Log](tasks.md)")
        files["tasks.md"] = f"# Task Log\n\n{task_log}"
    files["README.md"] = (
        f"# Orchestrator Session: {session_id}\n\n"
        f"**Date:** {timestamp}\n**Goal:** {goal}\n\n"
        f"## Contents\n\n" + "\n".join(toc) + "\n\n---\n*Generated by Orchestrator Self-Governing System*"
    )
    for fname, fcontent in files.items():
        with open(os.path.join(session_dir, fname), "w") as f:
            f.write(fcontent)
    latest_dir = os.path.join(os.path.dirname(OUTPUT_DIR), "latest")
    try:
        if os.path.islink(latest_dir):
            os.unlink(latest_dir)
        os.symlink(session_dir, latest_dir)
    except OSError:
        pass
    return f"Outputs saved to: {session_dir}/ (latest → outputs/latest)"


def _parse_severity(review: str) -> tuple[str, str]:
    """Parse the reviewer's verdict. Returns (severity, detail).
    
    Looks for **SEVERITY: <type>** first. Falls back to keyword scanning
    if no structured marker is found.
    """
    marker = re.search(r"\*\*SEVERITY:\s*([^*\n]+)\*\*", review, re.IGNORECASE)

    if marker:
        upper_verdict = marker.group(1).strip().upper()
        if "ALL MET" in upper_verdict or "NONE" in upper_verdict:
            return ("ALL MET", review)
        if "FAKE DATA" in upper_verdict:
            severity = "FAKE DATA"
        elif "TANGENT" in upper_verdict:
            severity = "TANGENT"
        elif "MISSING" in upper_verdict:
            severity = "MISSING"
        else:
            severity = "MISSING"
    else:
        # Fallback: scan full review for keywords
        upper = review.upper()
        if "ALL GOALS" in upper and "MET" in upper and "NOT MET" not in upper:
            return ("ALL MET", review)
        if "FAKE DATA" in upper or "FABRICATED" in upper or "HALLUCINATED" in upper:
            severity = "FAKE DATA"
        elif "TANGENT" in upper or "OFF-TOPIC" in upper or "OFF TOPIC" in upper:
            severity = "TANGENT"
        elif "MISSING" in upper or "INCOMPLETE" in upper or "GAP" in upper:
            severity = "MISSING"
        else:
            severity = "MISSING"
        print(f"  ⚠ No **SEVERITY:** marker found — using keyword fallback → {severity}")

    if severity == "MISSING":
        gaps_match = re.search(
            r"\*\*REMAINING GAPS:\*\*(.*?)(?:\n\*\*|\Z)",
            review, re.DOTALL
        )
        detail = gaps_match.group(1).strip() if gaps_match else review
    elif severity == "TANGENT":
        goal_match = re.search(
            r"\*\*ORIGINAL GOAL:\*\*(.*?)(?:\n\*\*|\Z)",
            review, re.DOTALL
        )
        detail = goal_match.group(1).strip() if goal_match else review
    elif severity == "FAKE DATA":
        ev_match = re.search(
            r"\*\*EVIDENCE:\*\*(.*?)(?:\n\*\*|\Z)",
            review, re.DOTALL
        )
        detail = ev_match.group(1).strip() if ev_match else review
    else:
        detail = review

    return (severity, detail)


async def run_orchestrator(goal: str, max_iterations: int = 5) -> str:
    from .planner_agent import run_planner
    from .reviewer_agent import run_reviewer

    session_id = uuid.uuid4().hex[:8]
    print(f"\n{'='*60}")
    print(f"  ORCHESTRATOR — Self-Governing Loop")
    print(f"  Session: {session_id}")
    print(f"  Goal: {goal}")
    print(f"{'='*60}")

    # Clear planner store for fresh session
    for f in os.listdir(PLANNER_STORE):
        try:
            os.remove(os.path.join(PLANNER_STORE, f))
        except OSError:
            pass

    _brain_save(f"Session {session_id}", f"Goal: {goal}", tags=["session"])
    _temp_save(f"{session_id}_goal", goal)

    current_goal = goal
    strictness = 0
    all_plans = []
    all_reviews = []

    for iteration in range(1, max_iterations + 1):
        print(f"\n{'─'*60}")
        print(f"  Iteration {iteration}/{max_iterations}")
        print(f"  Strictness level: {strictness}")
        print(f"{'─'*60}")

        # Refresh prior context from planner store (updated by previous iterations)
        prior_context = ""
        try:
            ctx_files = sorted([f for f in os.listdir(PLANNER_STORE) if f.startswith("ctx_") and f.endswith(".json")])
            for cf in ctx_files[-3:]:
                with open(os.path.join(PLANNER_STORE, cf)) as f:
                    data = json.load(f)
                    prior_context += f"\n--- Prior: {data['key']} ---\n{data['summary'][:1000]}\n"
        except (FileNotFoundError, json.JSONDecodeError):
            pass

        # Build planner prompt based on strictness
        plan_prompt_base = (
            f"You are the planner for iteration {iteration}. "
            f"Use `store_result(key, data)` after each delegate_to_agent call. "
            f"Use `load_result(key)` before the next call to include prior data. "
            f"At the end, use `store_context(\"iteration_{iteration}_summary\", summary)` "
            f"with a brief summary of what was done and what remains. "
            f"Your FINAL OUTPUT must contain the RAW DATA from each step, not process descriptions."
        )

        if strictness >= 2:
            plan_prompt_base += (
                "\n\nWARNING: Previous runs fabricated data. You MUST actually call delegate_to_agent "
                "for every step and store_result after each. Do NOT use placeholders. "
                "If a tool returns data, paste it verbatim into the DATA section."
            )
        elif strictness >= 1:
            plan_prompt_base += (
                "\n\nCRITICAL: You must store_result after each delegation and include raw data in your output. "
                "Verify any URLs with verify_links. Report real results only."
            )


        # If previous review failed, add explicit reviewer feedback and instruct planner to be more thorough
        reviewer_feedback = ""
        if iteration > 1 and severity != "ALL MET":
            reviewer_feedback = (
                f"\n\n---\n\n"
                f"# REVIEWER FEEDBACK (Iteration {iteration-1})\n"
                f"The last review found the plan or execution was NOT thorough enough.\n"
                f"Verdict: {severity}\n"
                f"Details: {detail}\n"
                f"\nYou MUST be more thorough in your research, tool use, and data gathering. Address every missing or incomplete point above. Do not skip steps. Provide concrete, raw data for each subgoal.\n"
            )
        plan_prompt = (
            plan_prompt_base + "\n\n"
            f"GOAL:\n{current_goal}\n\n"
            f"Prior context from previous iterations:\n{prior_context if prior_context else 'None yet'}\n"
            f"Recent plans and reviews:\n"
            + ("\n---\n".join(all_plans[-2:] + all_reviews[-2:]) if all_plans else "None yet")
            + reviewer_feedback
        )

        plan_result = await run_planner(plan_prompt)
        all_plans.append(f"Iteration {iteration} Plan:\n{plan_result}")
        _brain_save(f"Session {session_id} - Plan {iteration}", plan_result, tags=["plan", f"iteration-{iteration}"])

        # Review
        review_prompt = (
            f"Review these execution results against the goal.\n\n"
            f"GOAL:\n{current_goal}\n\n"
            f"EXECUTION RESULTS:\n{plan_result}\n\n"
            f"Output your verdict with the appropriate severity level."
        )
        review_result = await run_reviewer(review_prompt)
        all_reviews.append(f"Iteration {iteration} Review:\n{review_result}")
        _brain_save(f"Session {session_id} - Review {iteration}", review_result, tags=["review", f"iteration-{iteration}"])

        # Parse verdict
        severity, detail = _parse_severity(review_result)

        # If no structured verdict marker, re-run reviewer with strict instruction
        if "**SEVERITY:" not in review_result:
            print(f"  ⚠ Reviewer did not output **SEVERITY:** — re-running with strict instruction")
            retry_prompt = (
                f"Your previous review did not contain a structured verdict.\n\n"
                f"Review these execution results against the goal and output EXACTLY:\n"
                f"**SEVERITY: <TYPE>**\n\n"
                f"GOAL:\n{current_goal}\n\n"
                f"EXECUTION RESULTS:\n{plan_result}\n\n"
                f"Your verdict must be on its own line starting with **SEVERITY:"
            )
            review_result = await run_reviewer(retry_prompt)
            severity, detail = _parse_severity(review_result)

        if severity == "ALL MET":
            print(f"\n{'='*60}")
            print(f"  ✅ ALL GOALS MET — {iteration} iteration(s)")
            print(f"{'='*60}")
            # Print the final synthesis (main research report) to stdout
            if plan_result:
                print(f"\n===== FINAL REPORT =====\n{plan_result}\n=======================\n")
            final = (
                f"## Complete\n\n**Goal:** {goal}\n**Iterations:** {iteration}\n\n"
                f"### Plans & Execution\n" + "\n---\n".join(all_plans) + "\n\n"
                f"### Reviews\n" + "\n---\n".join(all_reviews)
            )
            await _save_outputs(
                session_id=session_id, goal=goal,
                plan="\n\n---\n\n".join(all_plans),
                execution_log="\n\n---\n\n".join(all_plans),
                review_report="\n\n---\n\n".join(all_reviews),
                final_synthesis=plan_result,
                task_log=f"Completed in {iteration} iteration(s)",
            )
            _brain_save(f"Session {session_id} - Complete", final, tags=["session-complete"])
            return final

        elif severity == "MISSING":
            print(f"\n  ⚠ MISSING — iteration {iteration + 1}")
            print(f"  Gaps: {detail[:200]}...")
            current_goal = (
                f"Original goal: {goal}\n\n"
                f"What's still missing:\n{detail}\n\n"
                f"Complete what's missing. Use prior results as context."
            )

        elif severity == "TANGENT":
            print(f"\n  ⚠ TANGENT — resending original goal")
            print(f"  Detail: {detail[:200]}...")
            current_goal = (
                f"ORIGINAL GOAL (previous attempt went off-topic):\n{goal}\n\n"
                f"Previous off-topic output was:\n{plan_result[:300]}...\n\n"
                f"Stay focused on the original goal above."
            )

        elif severity == "FAKE DATA":
            print(f"\n  ⚠ FAKE DATA — restarting with stricter prompt")
            print(f"  Evidence: {detail[:200]}...")
            strictness += 1
            current_goal = (
                f"STRICT RE-RUN. Original goal: {goal}\n\n"
                f"What went wrong:\n{detail}\n\n"
                f"You MUST actually call delegate_to_agent for every step. "
                f"No simulated or placeheld results. Call real tools with real parameters."
            )

    print(f"\n{'='*60}")
    print(f"  ⚠ Max iterations ({max_iterations}) reached")
    print(f"{'='*60}")
    return (
        f"## Max Iterations Reached\n\n"
        f"**Goal:** {goal}\n**Iterations:** {max_iterations}\n\n"
        f"### Plans\n" + "\n---\n".join(all_plans) + "\n\n"
        f"### Reviews\n" + "\n---\n".join(all_reviews)
    )
